8.2 主页面的pr
xhzq233/pivot_chat pull request #15
Opened 2023-08-02 13:41 UTC by niuniu0101

美化了主页面

2023-08-02 14:46 UTC, Mai-hh commented
Pr信息不明确❌
每个commit建议写清楚干了啥，不然不想review

2023-08-03 08:12 UTC, xhzq233 requested changes

2023-08-03 08:12 UTC, xhzq233 commented on README.md
> -- IM框架[flutter_openim_sdk](https://pub.dev/packages/flutter_openim_sdk)
你不应该把我的changes给丢弃了

2023-08-03 08:12 UTC, xhzq233 commented on lib/pages/chat/pc_chat_page_bloc.dart
> +import 'package:shared_preferences/shared_preferences.dart';
使用`spManager`，不要自己加package

2023-08-03 08:12 UTC, xhzq233 commented on pubspec.yaml
> +  bubble: ^1.2.1
这个bubble可以不用加。发送的文本简单的套个container就可以

2023-08-09 16:46 UTC, AmiyaSX commented on lib/pages/home/pc_home_page.dart
> +              },
这里所有群聊item点进去都是相同的chat页面（指聊天消息数据的源是一样的）是有问题的，界面UI框架可以复用，但是每个群聊的消息需要针对性地拉取，还有在跳转时应该有传参（群聊名称）展示在chat页面顶部。

2023-08-09 17:00 UTC, AmiyaSX commented on lib/pages/home/pc_home_page.dart
> +                style: TextStyle(fontSize: 12, color: Colors.purple[80]),
![3a110710-af20-4791-9089-747bdd7561b2](https://github.com/xhzq233/pivot_chat/assets/71491866/c9a6bfde-4e27-4cab-aad4-59ac844bc9b0)
另外这里布局注意调整，有溢出（上方的布局不要往下挤）

2023-08-10 02:50 UTC, niuniu0101 commented on lib/pages/home/pc_home_page.dart
> +                style: TextStyle(fontSize: 12, color: Colors.purple[80]),
这个我之前就遇到了，我才把id改成了四位数，不过好像是leading组件有空间限制，我再找找问题出在哪里

2023-08-13 13:38 UTC, AmiyaSX commented on lib/pages/home/pc_home_page.dart
> +                      ),
![image](https://github.com/xhzq233/pivot_chat/assets/71491866/782fa7b6-b3ad-4904-b051-88535c52a8d4)
ID还是被截断的，这个地方布局宽度最好不被上面限制（或者弄一个超出一定位数就省略显示的效果）。其他都没什么问题了，可以继续添加新界面和完善功能。

2023-08-13 14:03 UTC, xhzq233 commented on lib/pages/home/pc_home_page.dart
> +                      ),
注意设计稿上是：ID位于头像的右边，并且与头像底部对齐，可以优化一下

2023-08-16 19:07 UTC, outaink commented
感觉可以先合，UI问题等一个BugFix的PR

2023-08-17 01:10 UTC, xhzq233 commented
> 感觉可以先合，UI问题等一个BugFix的PR

文件冲突了，而且不应该从主分支合入

2023-11-10 04:22 UTC, closed without merging