Fix TODO
xhzq233/pivot_chat pull request #20
Opened 2023-11-17 14:37 UTC by YanShuq1

# feat(route):完成TODO项的页面跳转功能  
用户登录凭证过期或被踢下线时返回登录页，使用了GlobalKey进行无context跳转。

2023-11-17 15:02 UTC, xhzq233 requested changes

2023-11-17 15:02 UTC, xhzq233 commented on lib/im.dart
> +        navigatorKey.currentState?.push(LoginPage.route());
這裏應該是pop，比如當前用戶在聊天，應該登出后不允許該用戶繼續聊天，要把該頁面pop出去

2023-11-17 15:03 UTC, xhzq233 commented on lib/im.dart
> +        navigatorKey.currentState?.push(LoginPage.route());
修完就把TODO直接刪了就行0.0

2023-11-18 03:49 UTC, YanShuq1 commented on lib/im.dart
> +        navigatorKey.currentState?.push(LoginPage.route());
好嘟O.O

2023-11-18 08:43 UTC, xhzq233 commented on lib/im.dart
> +        navigatorKey.currentState?.push(LoginPage.route());
萬一當前頁面有多個呢，只pop一個是不是不行

2023-11-18 08:45 UTC, YanShuq1 commented on lib/im.dart
> +        navigatorKey.currentState?.push(LoginPage.route());
那我看看O.o

2023-11-18 08:57 UTC, YanShuq1 commented on lib/im.dart
> +        navigatorKey.currentState?.push(LoginPage.route());
那用pushNamedAndRemoveUntil方法可以做到但是要注册路由名字诶

2023-11-18 10:14 UTC, xhzq233 commented on lib/im.dart
> +        navigatorKey.currentState?.push(LoginPage.route());
既然有pushnamed，那肯定有push，你可以再看一看

2023-11-18 10:15 UTC, xhzq233 commented on lib/im.dart
> +        navigatorKey.currentState?.push(LoginPage.route());
你的format注意下

2023-11-18 17:22 UTC, YanShuq1 commented on lib/im.dart
> +        navigatorKey.currentState?.push(LoginPage.route());
什么format有问题O.o

2023-11-19 16:21 UTC, xhzq233 approved these changes

2023-11-19 16:21 UTC, xhzq233 commented on lib/pages/login/login_page.dart
commit前检查一下自己改动了什么，是不是有不该改动的

2023-11-19 16:22 UTC, merged